// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SafeHarbor.Data;

#nullable disable

namespace SafeHarbor.Migrations
{
    [DbContext(typeof(SafeHarborDbContext))]
    [Migration("20260410124410_AddHomeVisitDetailsFields")]
    partial class AddHomeVisitDetailsFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("lighthouse")
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SafeHarbor.Models.Entities.Campaign", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<DateTimeOffset?>("EndDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_date");

                    b.Property<decimal>("GoalAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("goal_amount");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("StartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_date");

                    b.Property<int>("StatusStateId")
                        .HasColumnType("integer")
                        .HasColumnName("status_state_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("StatusStateId");

                    b.ToTable("campaigns", "lighthouse");
                });

            modelBuilder.Entity("SafeHarbor.Models.Entities.CaseConference", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("ConferenceDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("conference_date");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("OutcomeSummary")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("outcome_summary");

                    b.Property<Guid>("ResidentCaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("resident_case_id");

                    b.Property<int>("StatusStateId")
                        .HasColumnType("integer")
                        .HasColumnName("status_state_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ResidentCaseId");

                    b.HasIndex("StatusStateId");

                    b.ToTable("case_conferences", "lighthouse");
                });

            modelBuilder.Entity("SafeHarbor.Models.Entities.Contribution", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("amount");

                    b.Property<Guid?>("CampaignId")
                        .HasColumnType("uuid")
                        .HasColumnName("campaign_id");

                    b.Property<DateTimeOffset>("ContributionDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("contribution_date");

                    b.Property<int>("ContributionTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("contribution_type_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Frequency")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("frequency");

                    b.Property<int>("StatusStateId")
                        .HasColumnType("integer")
                        .HasColumnName("status_state_id");

                    b.Property<Guid>("SupporterId")
                        .HasColumnType("uuid")
                        .HasColumnName("supporter_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("CampaignId");

                    b.HasIndex("ContributionTypeId");

                    b.HasIndex("StatusStateId");

                    b.HasIndex("SupporterId");

                    b.ToTable("contributions", "lighthouse");
                });

            modelBuilder.Entity("SafeHarbor.Models.Entities.ContributionAllocation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("AmountAllocated")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("amount_allocated");

                    b.Property<Guid>("ContributionId")
                        .HasColumnType("uuid")
                        .HasColumnName("contribution_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid>("SafehouseId")
                        .HasColumnType("uuid")
                        .HasColumnName("safehouse_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ContributionId");

                    b.HasIndex("SafehouseId");

                    b.ToTable("contribution_allocations", "lighthouse");
                });

            modelBuilder.Entity("SafeHarbor.Models.Entities.HomeVisit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("FamilyCooperationLevel")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("family_cooperation_level");

                    b.Property<string>("FollowUpActions")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("follow_up_actions");

                    b.Property<string>("HomeEnvironmentObservations")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("home_environment_observations");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<Guid>("ResidentCaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("resident_case_id");

                    b.Property<bool>("SafetyConcernsIdentified")
                        .HasColumnType("boolean")
                        .HasColumnName("safety_concerns_identified");

                    b.Property<int>("StatusStateId")
                        .HasColumnType("integer")
                        .HasColumnName("status_state_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<DateTimeOffset>("VisitDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("visit_date");

                    b.Property<int>("VisitTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("visit_type_id");

                    b.HasKey("Id");

                    b.HasIndex("ResidentCaseId");

                    b.HasIndex("StatusStateId");

                    b.HasIndex("VisitTypeId");

                    b.ToTable("home_visits", "lighthouse");
                });

            modelBuilder.Entity("SafeHarbor.Models.Entities.InterventionPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<DateTimeOffset>("EffectiveFrom")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("effective_from");

                    b.Property<DateTimeOffset?>("EffectiveTo")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("effective_to");

                    b.Property<string>("PlanDetails")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("plan_details");

                    b.Property<Guid>("ResidentCaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("resident_case_id");

                    b.Property<int>("StatusStateId")
                        .HasColumnType("integer")
                        .HasColumnName("status_state_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ResidentCaseId");

                    b.HasIndex("StatusStateId");

                    b.ToTable("intervention_plans", "lighthouse");
                });

            modelBuilder.Entity("SafeHarbor.Models.Entities.ProcessRecording", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("ConcernsFlagged")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("EmotionalStateEnd")
                        .HasColumnType("text");

                    b.Property<string>("EmotionalStateObserved")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FollowUpActions")
                        .HasColumnType("text");

                    b.Property<string>("InterventionsApplied")
                        .HasColumnType("text");

                    b.Property<string>("NotesRestricted")
                        .HasColumnType("text");

                    b.Property<bool>("ProgressNoted")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recorded_at");

                    b.Property<bool>("ReferralMade")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ResidentCaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("resident_case_id");

                    b.Property<int?>("SessionDurationMinutes")
                        .HasColumnType("integer");

                    b.Property<string>("SessionType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SocialWorker")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("summary");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ResidentCaseId");

                    b.ToTable("process_recordings", "lighthouse");
                });

            modelBuilder.Entity("SafeHarbor.Models.Entities.ResidentAssessment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("AssessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("assessed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<Guid>("ResidentCaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("resident_case_id");

                    b.Property<int>("StatusStateId")
                        .HasColumnType("integer")
                        .HasColumnName("status_state_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ResidentCaseId");

                    b.HasIndex("StatusStateId");

                    b.ToTable("resident_assessments", "lighthouse");
                });

            modelBuilder.Entity("SafeHarbor.Models.Entities.ResidentCase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("CaseCategoryId")
                        .HasColumnType("integer")
                        .HasColumnName("case_category_id");

                    b.Property<int?>("CaseSubcategoryId")
                        .HasColumnType("integer")
                        .HasColumnName("case_subcategory_id");

                    b.Property<DateTimeOffset?>("ClosedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("closed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<DateTimeOffset>("OpenedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("opened_at");

                    b.Property<Guid?>("ResidentId")
                        .HasColumnType("uuid")
                        .HasColumnName("resident_id");

                    b.Property<Guid>("SafehouseId")
                        .HasColumnType("uuid")
                        .HasColumnName("safehouse_id");

                    b.Property<int>("StatusStateId")
                        .HasColumnType("integer")
                        .HasColumnName("status_state_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("CaseCategoryId");

                    b.HasIndex("CaseSubcategoryId");

                    b.HasIndex("ResidentId");

                    b.HasIndex("SafehouseId");

                    b.HasIndex("StatusStateId");

                    b.ToTable("resident_cases", "lighthouse");
                });

            modelBuilder.Entity("SafeHarbor.Models.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("roles", "lighthouse");
                });

            modelBuilder.Entity("SafeHarbor.Models.Entities.Safehouse", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("region");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("safehouses", "lighthouse");
                });

            modelBuilder.Entity("SafeHarbor.Models.Entities.SocialPostMetric", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal?>("AttributedDonationAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("attributed_donation_amount");

                    b.Property<int?>("AttributedDonationCount")
                        .HasColumnType("integer")
                        .HasColumnName("attributed_donation_count");

                    b.Property<Guid?>("CampaignId")
                        .HasColumnType("uuid")
                        .HasColumnName("campaign_id");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content_type");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<int>("Engagements")
                        .HasColumnType("integer")
                        .HasColumnName("engagements");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("platform");

                    b.Property<DateTimeOffset>("PostedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("posted_at");

                    b.Property<int>("Reach")
                        .HasColumnType("integer")
                        .HasColumnName("reach");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("CampaignId");

                    b.ToTable("social_post_metrics", "lighthouse");
                });

            modelBuilder.Entity("SafeHarbor.Models.Entities.Supporter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<DateTimeOffset>("LastActivityAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_activity_at");

                    b.Property<decimal>("LifetimeDonations")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("lifetime_donations");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("PaymentToken")
                        .HasColumnType("text")
                        .HasColumnName("payment_token");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.ToTable("supporters", "lighthouse");
                });

            modelBuilder.Entity("SafeHarbor.Models.Entities.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("f_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("l_name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.Property<long?>("SupporterId")
                        .HasColumnType("bigint")
                        .HasColumnName("supporter_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("UserId");

                    b.ToTable("users", "lighthouse");
                });

            modelBuilder.Entity("SafeHarbor.Models.Entities.UserProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("external_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("user_profiles", "lighthouse");
                });

            modelBuilder.Entity("SafeHarbor.Models.Entities.UserRole", b =>
                {
                    b.Property<Guid>("UserProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_profile_id");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.HasKey("UserProfileId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("user_roles", "lighthouse");
                });

            modelBuilder.Entity("SafeHarbor.Models.Lookups.CaseCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("case_category", "lighthouse");
                });

            modelBuilder.Entity("SafeHarbor.Models.Lookups.CaseSubcategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CaseCategoryId")
                        .HasColumnType("integer")
                        .HasColumnName("case_category_id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("CaseCategoryId");

                    b.ToTable("case_subcategory", "lighthouse");
                });

            modelBuilder.Entity("SafeHarbor.Models.Lookups.ContributionType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("contribution_type", "lighthouse");
                });

            modelBuilder.Entity("SafeHarbor.Models.Lookups.StatusState", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<int>("Domain")
                        .HasColumnType("integer")
                        .HasColumnName("domain");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("status_state", "lighthouse");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "active",
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "system",
                            Domain = 0,
                            Name = "Active",
                            UpdatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = 2,
                            Code = "pending",
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "system",
                            Domain = 0,
                            Name = "Pending",
                            UpdatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = 3,
                            Code = "closed",
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "system",
                            Domain = 0,
                            Name = "Closed",
                            UpdatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("SafeHarbor.Models.Lookups.VisitType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("visit_type", "lighthouse");
                });

            modelBuilder.Entity("SafeHarbor.Models.Resident", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CaseWorkerEmail")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("case_worker_email");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date")
                        .HasColumnName("date_of_birth");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("full_name");

                    b.Property<string>("MedicalNotes")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("medical_notes");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.ToTable("residents", "lighthouse");
                });

            modelBuilder.Entity("SafeHarbor.Models.Entities.Campaign", b =>
                {
                    b.HasOne("SafeHarbor.Models.Lookups.StatusState", "StatusState")
                        .WithMany()
                        .HasForeignKey("StatusStateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StatusState");
                });

            modelBuilder.Entity("SafeHarbor.Models.Entities.CaseConference", b =>
                {
                    b.HasOne("SafeHarbor.Models.Entities.ResidentCase", "ResidentCase")
                        .WithMany("CaseConferences")
                        .HasForeignKey("ResidentCaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SafeHarbor.Models.Lookups.StatusState", "StatusState")
                        .WithMany()
                        .HasForeignKey("StatusStateId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ResidentCase");

                    b.Navigation("StatusState");
                });

            modelBuilder.Entity("SafeHarbor.Models.Entities.Contribution", b =>
                {
                    b.HasOne("SafeHarbor.Models.Entities.Campaign", "Campaign")
                        .WithMany("Contributions")
                        .HasForeignKey("CampaignId");

                    b.HasOne("SafeHarbor.Models.Lookups.ContributionType", "ContributionType")
                        .WithMany()
                        .HasForeignKey("ContributionTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SafeHarbor.Models.Lookups.StatusState", "StatusState")
                        .WithMany()
                        .HasForeignKey("StatusStateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SafeHarbor.Models.Entities.Supporter", "Supporter")
                        .WithMany("Contributions")
                        .HasForeignKey("SupporterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Campaign");

                    b.Navigation("ContributionType");

                    b.Navigation("StatusState");

                    b.Navigation("Supporter");
                });

            modelBuilder.Entity("SafeHarbor.Models.Entities.ContributionAllocation", b =>
                {
                    b.HasOne("SafeHarbor.Models.Entities.Contribution", "Contribution")
                        .WithMany("Allocations")
                        .HasForeignKey("ContributionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SafeHarbor.Models.Entities.Safehouse", "Safehouse")
                        .WithMany()
                        .HasForeignKey("SafehouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contribution");

                    b.Navigation("Safehouse");
                });

            modelBuilder.Entity("SafeHarbor.Models.Entities.HomeVisit", b =>
                {
                    b.HasOne("SafeHarbor.Models.Entities.ResidentCase", "ResidentCase")
                        .WithMany("HomeVisits")
                        .HasForeignKey("ResidentCaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SafeHarbor.Models.Lookups.StatusState", "StatusState")
                        .WithMany()
                        .HasForeignKey("StatusStateId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("SafeHarbor.Models.Lookups.VisitType", "VisitType")
                        .WithMany()
                        .HasForeignKey("VisitTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ResidentCase");

                    b.Navigation("StatusState");

                    b.Navigation("VisitType");
                });

            modelBuilder.Entity("SafeHarbor.Models.Entities.InterventionPlan", b =>
                {
                    b.HasOne("SafeHarbor.Models.Entities.ResidentCase", "ResidentCase")
                        .WithMany("InterventionPlans")
                        .HasForeignKey("ResidentCaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SafeHarbor.Models.Lookups.StatusState", "StatusState")
                        .WithMany()
                        .HasForeignKey("StatusStateId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ResidentCase");

                    b.Navigation("StatusState");
                });

            modelBuilder.Entity("SafeHarbor.Models.Entities.ProcessRecording", b =>
                {
                    b.HasOne("SafeHarbor.Models.Entities.ResidentCase", "ResidentCase")
                        .WithMany("ProcessRecordings")
                        .HasForeignKey("ResidentCaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ResidentCase");
                });

            modelBuilder.Entity("SafeHarbor.Models.Entities.ResidentAssessment", b =>
                {
                    b.HasOne("SafeHarbor.Models.Entities.ResidentCase", "ResidentCase")
                        .WithMany("Assessments")
                        .HasForeignKey("ResidentCaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SafeHarbor.Models.Lookups.StatusState", "StatusState")
                        .WithMany()
                        .HasForeignKey("StatusStateId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ResidentCase");

                    b.Navigation("StatusState");
                });

            modelBuilder.Entity("SafeHarbor.Models.Entities.ResidentCase", b =>
                {
                    b.HasOne("SafeHarbor.Models.Lookups.CaseCategory", "CaseCategory")
                        .WithMany()
                        .HasForeignKey("CaseCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SafeHarbor.Models.Lookups.CaseSubcategory", "CaseSubcategory")
                        .WithMany()
                        .HasForeignKey("CaseSubcategoryId");

                    b.HasOne("SafeHarbor.Models.Resident", "Resident")
                        .WithMany()
                        .HasForeignKey("ResidentId");

                    b.HasOne("SafeHarbor.Models.Entities.Safehouse", "Safehouse")
                        .WithMany("ResidentCases")
                        .HasForeignKey("SafehouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SafeHarbor.Models.Lookups.StatusState", "StatusState")
                        .WithMany()
                        .HasForeignKey("StatusStateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CaseCategory");

                    b.Navigation("CaseSubcategory");

                    b.Navigation("Resident");

                    b.Navigation("Safehouse");

                    b.Navigation("StatusState");
                });

            modelBuilder.Entity("SafeHarbor.Models.Entities.SocialPostMetric", b =>
                {
                    b.HasOne("SafeHarbor.Models.Entities.Campaign", "Campaign")
                        .WithMany("SocialPostMetrics")
                        .HasForeignKey("CampaignId");

                    b.Navigation("Campaign");
                });

            modelBuilder.Entity("SafeHarbor.Models.Entities.UserRole", b =>
                {
                    b.HasOne("SafeHarbor.Models.Entities.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SafeHarbor.Models.Entities.UserProfile", "UserProfile")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("SafeHarbor.Models.Lookups.CaseSubcategory", b =>
                {
                    b.HasOne("SafeHarbor.Models.Lookups.CaseCategory", "CaseCategory")
                        .WithMany("Subcategories")
                        .HasForeignKey("CaseCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CaseCategory");
                });

            modelBuilder.Entity("SafeHarbor.Models.Entities.Campaign", b =>
                {
                    b.Navigation("Contributions");

                    b.Navigation("SocialPostMetrics");
                });

            modelBuilder.Entity("SafeHarbor.Models.Entities.Contribution", b =>
                {
                    b.Navigation("Allocations");
                });

            modelBuilder.Entity("SafeHarbor.Models.Entities.ResidentCase", b =>
                {
                    b.Navigation("Assessments");

                    b.Navigation("CaseConferences");

                    b.Navigation("HomeVisits");

                    b.Navigation("InterventionPlans");

                    b.Navigation("ProcessRecordings");
                });

            modelBuilder.Entity("SafeHarbor.Models.Entities.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("SafeHarbor.Models.Entities.Safehouse", b =>
                {
                    b.Navigation("ResidentCases");
                });

            modelBuilder.Entity("SafeHarbor.Models.Entities.Supporter", b =>
                {
                    b.Navigation("Contributions");
                });

            modelBuilder.Entity("SafeHarbor.Models.Entities.UserProfile", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("SafeHarbor.Models.Lookups.CaseCategory", b =>
                {
                    b.Navigation("Subcategories");
                });
#pragma warning restore 612, 618
        }
    }
}
